version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./frontend
      args:
        - API_URL=http://localhost:3000
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - backend
