export const BUTTONS = {
  start: 'Start',
  stop: 'Stop',
  send: 'Send',
  autoRecord: 'Auto record',
  uploadPdf: 'Upload pdf file',
  download: 'Download',
  addUser: 'Add user',
  register: 'Register',
  login: 'Log in',
  add: 'Add',
  remove: 'Remove',
}

export const TEXTS = {
  questionRegister: 'Already registered? Log in',
  questionLogin: 'Not registered yet? Register',
  registerHeader: 'Registration',
  loginHeader: 'Log In',
  addHeader: 'Add User',
  headAdmin: 'Admin panel',
  headGeneral: 'Users',
  username: 'Username',
  action: 'Action',
  metrics: 'Metrics',
  algolia: 'algolia',
  humantic: 'humantic',
  headPRE: 'PRE Section',
  recordedText: 'Recorded text',
  dateAdded: 'Date added',
  linkedin: 'Amount of linkedin profiles',
}
